name: Build Linux Test Version

# Trigger on push to the main branch
on:
  push:
    branches:
      - 'main'
  workflow_dispatch: # Allow manual trigger from GitHub Actions UI

# If previous workflow is still running, we push again, we will cancel the previous workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  Build-Linux:
    name: Build Linux
    uses: ./.github/workflows/build-linux.yml